# Generated by Django 3.1.1 on 2020-09-24 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mycart', '0002_auto_20200919_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contect',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(default='', max_length=40)),
                ('Email', models.CharField(default='', max_length=40)),
                ('Phone', models.CharField(default='', max_length=12)),
                ('N_help', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
