# Generated by Django 3.1.1 on 2020-09-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mycart', '0004_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Address',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='order',
            name='City',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='order',
            name='Email',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='order',
            name='Name',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='order',
            name='Phone',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='order',
            name='State',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='order',
            name='Zip',
            field=models.CharField(default='', max_length=400),
        ),
    ]
